### ISSUE TITLE
Proposal: Allow returning arbitrary values from useEffect

### ISSUE THREAD

**Issue by tom95** [cmfcmf/ReactS#2]
Right now, one has to make sure that useEffect ends with a nil since closure always return their last expression in Smalltalk. Instead, we could only consider a return expression a cleanup if it is a block. Placing an unevaluated block as last statement fortunately would not make sense in any other way, since it's effectively a no-op, so this should signal the user's intent unambiguously.

**Comment by cmfcmf** [comment]
I typed a long response, but ended up deleting it when I realized what you meant by "Placing an unevaluated block as last statement fortunately would not make sense in any other way" (which took me way too long to grasp :D). So I agree, we can make this DX improvement. 👍
