### ISSUE TITLE
Windows CI?

### ISSUE THREAD

**Issue by tom95** [cmfcmf/ReactS#7]
The MorphicTestingFramework currently fails loading on Windows, leading to CI failures for ReactS, too. Is there any specific reason for testing on multiple OS for ReactS? Otherwise, we may just drop it. If there is a good reason I'll investigate fixing the MorphicTestingFramework :)

**Comment by cmfcmf** [comment]
There is no super specific reason other than that I wanted to make sure that the code works on Windows and Linux. Given that The MorphicTestingFramework is a test-only dependency, and it only breaks on Trunk, it doesn't matter much I guess. However, generally speaking, I would like to keep testing on multiple OSs. I excluded the combination of Squeak Trunk and Windows for now though, so everybody should get fewer annoying emails :)
