### ISSUE TITLE
Rationale of no-hooks-as-props Warning

### ISSUE THREAD

**Issue by tom95** [cmfcmf/ReactS#9]
In https://github.com/cmfcmf/ReactS/blob/main/packages/Cmfcmf-React-Core.package/CMFReactNodeComponent.class/instance/props..st#L5 the code throws an error if a hook is passed into the props. However, we commonly had the use case of passing the setter of a useState to another component. Do you remember what the rationale was to include this warning? Was it about hiding a data dependency because the hook won't change its identity?

**Comment by cmfcmf** [comment]
> Was it about hiding a data dependency because the hook won't change its identity

Yes, exactly. The component you pass a `useState` hook to would not re-render if the state changes. This is why the `useState` hook has a `setter` method to retrieve its setter.

**Comment by tom95** [comment]
Ah thanks for the pointer to the `setter` getter :) Makes perfect sense and should cover almost all use cases perfectly!
